# Generated by Django 4.2.16 on 2024-10-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_url', models.URLField(help_text='URL of the audio file for analysis.')),
                ('transcript_text', models.TextField(help_text='Transcribed text from the audio.')),
                ('emotion', models.CharField(help_text='Predicted emotion label.', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence level of the emotion prediction.')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the analysis.')),
            ],
            options={
                'verbose_name': 'Audio Emotion Analysis',
                'verbose_name_plural': 'Audio Emotion Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the emotion category.', max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of the emotion.')),
            ],
            options={
                'verbose_name': 'Emotion Category',
                'verbose_name_plural': 'Emotion Categories',
            },
        ),
        migrations.CreateModel(
            name='TextEmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='The text to be analyzed for emotions.')),
                ('emotion', models.CharField(help_text='Predicted emotion label.', max_length=50)),
                ('confidence_score', models.FloatField(help_text='Confidence level of the emotion prediction.')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the analysis.')),
            ],
            options={
                'verbose_name': 'Text Emotion Analysis',
                'verbose_name_plural': 'Text Emotion Analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
