# Generated by Django 4.2.16 on 2024-10-31 23:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionCategory',
        ),
        migrations.RemoveField(
            model_name='audioemotionanalysis',
            name='audio_file_url',
        ),
        migrations.AddField(
            model_name='audioemotionanalysis',
            name='audio_file',
            field=models.FileField(default=django.utils.timezone.now, help_text='Uploaded audio file for analysis.', upload_to='audio_files/'),
            preserve_default=False,
        ),
    ]
